# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2022-11-24 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_message', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='body',
            field=models.TextField(verbose_name='\u0422\u0435\u043b\u043e \u0448\u0430\u0431\u043b\u043e\u043d\u0430'),
        ),
    ]
