# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2022-11-24 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_message', '0002_auto_20221124_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_sent',
            field=models.BooleanField(default=False, verbose_name='\u041e\u0442\u043f\u043b\u0430\u0432\u043b\u0435\u043d\u043e'),
        ),
        migrations.AddField(
            model_name='message',
            name='subject',
            field=models.CharField(default='Subject', max_length=300, verbose_name='\u0422\u0435\u043c\u0430 \u043f\u0438\u0441\u044c\u043c\u0430'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='recipients',
            field=models.ManyToManyField(blank=True, help_text='\u041e\u0441\u0442\u0430\u0432\u0438\u0442\u044c \u043f\u0443\u0441\u0442\u044b\u043c \u0435\u0441\u043b\u0438 \u043d\u0430\u0434\u043e \u043e\u0442\u043f\u0440\u0430\u0432\u0438\u0442\u044c \u0432\u0441\u0435\u043c', related_name='messages', to='subscribers.Subscriber', verbose_name='\u041f\u043e\u043b\u0443\u0447\u0430\u0442\u0435\u043b\u0438'),
        ),
    ]
