# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2022-11-24 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_message', '0003_auto_20221124_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='is_sent',
            field=models.BooleanField(default=False, verbose_name='\u041e\u0442\u043f\u0440\u0430\u0432\u043b\u0435\u043d\u043e'),
        ),
    ]
